import type { Category, Municipality } from './types';

export const CATEGORY_LABELS: Record<Category, string> = {
  refeicoes: 'Refeições',
  pizzas: 'Pizzas',
  bebidas: 'Bebidas',
};

export const MUNICIPALITY_TABLE = {
  source: 'Taxas de referência — entrega por motorizada em Luanda',
  base: 292.5,
  perKm: 51.3,
  includedKm: 2.3,
  validUntil: '08.09.2026',
  note: 'Taxa = máximo(292,50 Kz; 292,50 Kz + 51,30 Kz × (distância − 2,3 km)), arredondada a múltiplos de 50 Kz.',
};

export const initialProducts = [
  {
    id: 'frango-funge',
    name: 'Frango Grelhado com Funge',
    description: 'Meio frango grelhado no carvão, servido com funge quente e molho de palma.',
    price: 4500,
    category: 'refeicoes' as Category,
    image: '/images/frango-funge.jpg',
    tags: ['Mais vendido', 'Grelhado'],
    available: true,
    featured: true,
    sort: 1,
  },
  {
    id: 'calulu',
    name: 'Calulu de Peixe',
    description: 'Calulu tradicional de peixe seco com quiabo, espinafre e óleo de palma. Acompanha funge.',
    price: 5000,
    category: 'refeicoes' as Category,
    image: '/images/calulu.jpg',
    tags: ['Tradicional'],
    available: true,
    featured: true,
    sort: 2,
  },
  {
    id: 'mufete',
    name: 'Mufete',
    description: 'Peixe inteiro grelhado com feijão de óleo de palma, farofa, cebola e limão.',
    price: 6500,
    category: 'refeicoes' as Category,
    image: '/images/mufete.jpg',
    tags: ['Sabores de Angola'],
    available: true,
    featured: true,
    sort: 3,
  },
  {
    id: 'feijoada',
    name: 'Feijoada à Aliado',
    description: 'Feijoada rica com carne de porco, chouriço e legumes, servida com arroz branco.',
    price: 5200,
    category: 'refeicoes' as Category,
    image: '/images/feijoada.jpg',
    tags: ['Familiar'],
    available: true,
    featured: false,
    sort: 4,
  },
  {
    id: 'arroz-marisco',
    name: 'Arroz de Marisco',
    description: 'Arroz de marisco com camarão, mexilhão, lula e toque de limão. Para partilhar.',
    price: 9800,
    category: 'refeicoes' as Category,
    image: '/images/arroz-marisco.jpg',
    tags: ['Especial', 'Para partilhar'],
    available: true,
    featured: true,
    sort: 5,
  },
  {
    id: 'churrasco',
    name: 'Churrasco Misto',
    description: 'Espetadas de carne de porco com piri-piri, mandioca frita e salada fresca.',
    price: 5800,
    category: 'refeicoes' as Category,
    image: '/images/churrasco.jpg',
    tags: ['Grelhado'],
    available: true,
    featured: false,
    sort: 6,
  },
  {
    id: 'pizza-margherita',
    name: 'Pizza Margherita',
    description: 'Molho de tomate fresco, mozzarella derretida e manjericão. Massa artesanal.',
    price: 4800,
    category: 'pizzas' as Category,
    image: '/images/pizza-margherita.jpg',
    tags: ['Vegetariana'],
    available: true,
    featured: true,
    sort: 7,
  },
  {
    id: 'pizza-frango',
    name: 'Pizza Frango & Cogumelos',
    description: 'Frango grelhado, cogumelos, pimentos, cebola roxa e muito queijo.',
    price: 6200,
    category: 'pizzas' as Category,
    image: '/images/pizza-frango.jpg',
    tags: ['Popular'],
    available: true,
    featured: true,
    sort: 8,
  },
  {
    id: 'pizza-chocolate',
    name: 'Pizza de Chocolate',
    description: 'Chocolate derretido, banana e morango com açúcar em pó. Sobremesa surpreendente.',
    price: 4200,
    category: 'pizzas' as Category,
    image: '/images/pizza-chocolate.jpg',
    tags: ['Sobremesa'],
    available: true,
    featured: true,
    sort: 9,
  },
  {
    id: 'sumo-manga',
    name: 'Sumo de Manga',
    description: 'Sumo natural de manga feito no momento, servido fresco com gelo.',
    price: 1200,
    category: 'bebidas' as Category,
    image: '/images/sumo-manga.svg',
    tags: ['Natural'],
    available: true,
    featured: false,
    sort: 10,
  },
  {
    id: 'refrigerante',
    name: 'Refrigerante',
    description: 'Refrigerante 350 ml — Coca-Cola, Fanta, Sprite e outras.',
    price: 800,
    category: 'bebidas' as Category,
    image: '/images/refrigerante.svg',
    tags: ['350 ml'],
    available: true,
    featured: false,
    sort: 11,
  },
  {
    id: 'agua',
    name: 'Água Mineral',
    description: 'Água mineral 1,5 L, com ou sem gás, sempre fresca.',
    price: 600,
    category: 'bebidas' as Category,
    image: '/images/agua.svg',
    tags: ['Gelada'],
    available: true,
    featured: false,
    sort: 12,
  },
];

/**
 * Municípios da província de Luanda. As taxas seguem a tabela de referência
 * de entregas por motorizada e a distância estimada a partir do ponto de
 * venda central da Aliado Food. Podem ser editadas no painel de administração.
 */
export const initialMunicipalities: Municipality[] = [
  { id: 1, name: 'Ingombota', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 2.5, estMinutes: 15, adjustment: 0, active: true, sort: 1 },
  { id: 2, name: 'Maianga', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 4.5, estMinutes: 20, adjustment: 0, active: true, sort: 2 },
  { id: 3, name: 'Sambizanga', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 6, estMinutes: 25, adjustment: 0, active: true, sort: 3 },
  { id: 4, name: 'Rangel', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 8, estMinutes: 30, adjustment: 0, active: true, sort: 4 },
  { id: 5, name: 'Cazenga', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 12, estMinutes: 35, adjustment: 0, active: true, sort: 5 },
  { id: 6, name: 'Cacuaco', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 16, estMinutes: 40, adjustment: 0, active: true, sort: 6 },
  { id: 7, name: 'Kilamba Kiaxi', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 14, estMinutes: 35, adjustment: 0, active: true, sort: 7 },
  { id: 8, name: 'Talatona', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 15, estMinutes: 35, adjustment: 0, active: true, sort: 8 },
  { id: 9, name: 'Belas', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 20, estMinutes: 45, adjustment: 0, active: true, sort: 9 },
  { id: 10, name: 'Viana', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 25, estMinutes: 50, adjustment: 0, active: true, sort: 10 },
  { id: 11, name: 'Quiçama', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 45, estMinutes: 80, adjustment: 0, active: true, sort: 11 },
  { id: 12, name: 'Ícolo e Bengo', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 55, estMinutes: 90, adjustment: 0, active: true, sort: 12 },
  { id: 13, name: 'Benfica', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 18, estMinutes: 40, adjustment: 0, active: true, sort: 13 },
  { id: 14, name: 'Cazenga — Kikolo', province: 'Luanda', baseFee: 292.5, perKm: 51.3, distanceKm: 13, estMinutes: 32, adjustment: 0, active: true, sort: 14 },
];

export const initialPartners = [
  {
    id: 1,
    name: 'Campo de Refrigerantes',
    description: 'Bebidas refrigerantes oficiais da Aliado Food.',
    image: '/images/partner-1.svg',
    url: '',
    active: true,
    sort: 1,
  },
  {
    id: 2,
    name: 'Fazenda Kiluanje',
    description: 'Produtos hortícolas frescos, todos os dias.',
    image: '/images/partner-2.svg',
    url: '',
    active: true,
    sort: 2,
  },
  {
    id: 3,
    name: 'Cervejeira Kirin',
    description: 'Parceira de bebidas e eventos da Aliado Food.',
    image: '/images/partner-3.svg',
    url: '',
    active: true,
    sort: 3,
  },
  {
    id: 4,
    name: 'Rede de Estafetas Aliado',
    description: 'Entregas rápidas por motorizada em toda a cidade.',
    image: '/images/partner-4.svg',
    url: '',
    active: true,
    sort: 4,
  },
];

export const initialActivities = [
  {
    id: 1,
    title: 'Noite de Sabores Angola',
    description: 'Degustação de pratos tradicionais angolanos com música ao vivo e djembes.',
    image: '/images/evento-noite-de-sabores.svg',
    eventDate: '',
    location: 'Ponto de venda Aliado Food',
    active: true,
    sort: 1,
  },
  {
    id: 2,
    title: 'Festival da Pizza',
    description: 'Pizzas artesanais com criatividade local, promoções e prémios para os clientes.',
    image: '/images/evento-festival-pizza.svg',
    eventDate: '',
    location: 'Ponto de venda Aliado Food',
    active: true,
    sort: 2,
  },
  {
    id: 3,
    title: 'Brunch de Família',
    description: 'Manhãs de brunch para toda a família, com atividades para os mais pequenos.',
    image: '/images/evento-brunch.svg',
    eventDate: '',
    location: 'Ponto de venda Aliado Food',
    active: true,
    sort: 3,
  },
];

export const initialCouriers = [
  { id: 1, name: 'José Miguel', phone: '+244 923 111 222', motorcycle: 'Honda Biz 125', zone: 'Luanda — Centro / Maianga', available: true, rating: 4.8, active: true },
  { id: 2, name: 'Pedro Domingos', phone: '+244 924 333 444', motorcycle: 'Yamaha Crypton', zone: 'Talatona / Belas / Benfica', available: true, rating: 4.6, active: true },
  { id: 3, name: 'Carlos Alberto', phone: '+244 925 555 666', motorcycle: 'Suzuki Address', zone: 'Cazenga / Kilamba Kiaxi', available: false, rating: 4.7, active: true },
  { id: 4, name: 'Manuel dos Santos', phone: '+244 926 777 888', motorcycle: 'Bajaj Boxer', zone: 'Viana / Cacuaco', available: true, rating: 4.5, active: true },
];

export const JOB_POSITIONS = [
  'Estafeta / Entregador',
  'Cozinheiro(a)',
  'Atendente de balcão',
  'Operador de encomendas',
  'Marketing e redes sociais',
  'Outro',
];
